from docx import Document
from docx.shared import Inches
import pyttsx3

def speak(text):
    pyttsx3.speak(text)


pyttsx3.speak('Welcome to our learning centre?')

document = Document()

# name phone number and email details
name = input('What is your name?  ')
speak('Hello'+ name +'How are you today?')
speak('what is your phone number?')
phone_number = input('What is your phone number? ')
speak('Is this number correct?'+ phone_number)
email = input('What is your email? ')


document.add_paragraph( name + ' ' + phone_number + ' '+ email)
# profile picture
document.add_picture(
    'capture001.png',
    width = Inches(2.0))

    # about me
document.add_heading('About me')
about_me = input('Tell about your self? ')
document.add_paragraph(about_me)

#work experience
document.add_heading('Work Experience')
p = document.add_paragraph()
company = input('Enter company ')
from_date = input('From Date ')
to_date = input('To Date ')

p.add_run(company +' ').bold = True
p.add_run(from_date + ' - ' + to_date + '\n').italic = True

experience_details = input(
    'Describe your experience at  ' + company)
p.add_run(experience_details)

# more experience_details
while True:
    has_more_experiences = input(
        'Do you have more experiences? Yes or NO')
    if has_more_experiences.lower() == 'yes':

        p = document.add_paragraph()
        company = input('Enter company ')
        from_date = input('From Date ')
        to_date = input('To Date ')

        p.add_run(company +' ').bold = True
        p.add_run(from_date + ' - ' + to_date + '\n').italic = True

        experience_details = input('Describe your experience at  ' + company)
        p.add_run(experience_details)
    else:
        break

# skills
document.add_heading('Skills')
skill = input('Enter Skill: ')
p = document.add_paragraph(skill)

p.style ='List Bullet'

    # more skills
while True:
    has_more_skills = input(
        'Do you have more skills? Yes or NO')
    if has_more_skills.lower() == 'yes':

        skill = input('Enter skill: ')
        p = document.add_paragraph(skill)
        p.style ='List Bullet'

    else:
        break

section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text ='CV generated by learning Python'

document.save('cv.docx')
